set rtp+=$HOME/.vim/vundle
call vundle#rc()

Bundle "ctrlp.vim"
Bundle "ack.vim"
Bundle "https://github.com/scrooloose/nerdtree.git"
Bundle "tComment"
Bundle "https://github.com/tpope/vim-fugitive.git"

Bundle "VimClojure"
Bundle "https://github.com/vim-ruby/vim-ruby.git"
Bundle "pyflakes.vim"
Bundle "scala.vim"
Bundle "snipMate"

" Bundle "Markdown"
" Bundle "Gist.vim"
Bundle "Jinja"
Bundle "https://github.com/flazz/vim-colorschemes.git"
Bundle "Solarized"
Bundle "https://github.com/kevinjqiu/vim-slime.git"
Bundle "surround.vim"
Bundle "ZoomWin"
Bundle "git://github.com/kevinjqiu/spectrum.vim.git"
Bundle "SQLUtilities"
Bundle "SuperTab-continued."
Bundle "git://github.com/pangloss/vim-javascript.git"
Bundle "https://github.com/vim-scripts/vim-coffee-script.git"
Bundle "https://github.com/Lokaltog/vim-powerline.git"
Bundle "https://github.com/sickill/vim-monokai.git"
Bundle "https://github.com/majutsushi/tagbar.git"
Bundle "https://github.com/sjl/badwolf.git"
Bundle "https://github.com/Lokaltog/vim-easymotion.git"
